# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hp/projects/moj-pardaz/xilinx/vivado/Zynq_Serial_Port/Zynq_Serial_Port.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_bram_ctrl_0_0/Base_Zynq_MPSoC_axi_bram_ctrl_0_0.xci
# IP: The module: 'Base_Zynq_MPSoC_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hp/projects/moj-pardaz/xilinx/vivado/Zynq_Serial_Port/Zynq_Serial_Port.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_bram_ctrl_0_0/Base_Zynq_MPSoC_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/hp/projects/moj-pardaz/xilinx/vivado/Zynq_Serial_Port/Zynq_Serial_Port.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_bram_ctrl_0_0/Base_Zynq_MPSoC_axi_bram_ctrl_0_0.xci
# IP: The module: 'Base_Zynq_MPSoC_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hp/projects/moj-pardaz/xilinx/vivado/Zynq_Serial_Port/Zynq_Serial_Port.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_bram_ctrl_0_0/Base_Zynq_MPSoC_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
